<?php
    require_once APPROOT . '/views/includes/head.php';
?>
    <div class="container">
    <?php
        require_once APPROOT . '/views/includes/navigation.php';
    ?>
        <div class="content">
            <h1>About</h1>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et quidem assumenda aliquid vel totam beatae ut repudiandae nesciunt sit, maiores tempora rem ullam dignissimos aliquam itaque optio. Sapiente ab consectetur voluptatibus quidem laboriosam repellendus, sint id aspernatur quibusdam ad numquam velit ea dolore asperiores quo necessitatibus vel non perspiciatis voluptas dicta quam magnam? Corrupti tenetur aspernatur cumque iste id non. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore vel fugiat placeat optio consectetur nihil quasi eum distinctio eos reprehenderit mollitia, natus iusto harum. Eos vitae aspernatur vero numquam eius accusantium omnis voluptatum, asperiores officia molestiae. Deleniti nemo sunt amet.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo asperiores in mollitia a atque sint nam saepe voluptas natus voluptate dolores, accusamus aliquam cupiditate consectetur tempore soluta hic ipsa neque omnis vel quos molestias. Veniam, aut. Hic minima perferendis laudantium fugit dolores tempora soluta esse cum, nemo ratione possimus sequi inventore nihil quam tenetur? Similique, explicabo nihil. Et reiciendis ex molestias obcaecati, est delectus quod repellendus iste non voluptatem adipisci libero? Perferendis earum quibusdam minus, quam maiores incidunt nisi, alias doloremque necessitatibus voluptate eum ad consectetur, impedit velit. Repellat aliquid deserunt pariatur obcaecati magni. Optio consectetur expedita soluta molestias ipsum.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate repellendus debitis fugit, asperiores obcaecati amet facilis est consequuntur, maxime quo magnam quas sapiente? Soluta quod voluptas, dolorum maiores rem expedita cumque distinctio optio neque fuga quam aut ipsum sed repudiandae dignissimos ullam vero esse dolor laboriosam impedit mollitia? Atque, adipisci. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos soluta illo placeat ex reiciendis a ea. Velit, dolor. Dolores libero, voluptate, nemo fuga, cupiditate sequi rerum aliquam minus inventore aspernatur perspiciatis! Cum, maxime! Necessitatibus porro cum fuga quam ratione corrupti autem earum, aut mollitia architecto nesciunt quo harum id hic cupiditate. Voluptate fuga eos praesentium recusandae suscipit sit iste ipsum natus quis vitae ratione similique, possimus rerum aut perspiciatis quod corporis tempore magnam doloremque neque quia perferendis. Velit facere aliquam explicabo. Ab illum excepturi, vitae esse corrupti quisquam voluptates aliquid!</p>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et quidem assumenda aliquid vel totam beatae ut repudiandae nesciunt sit, maiores tempora rem ullam dignissimos aliquam itaque optio. Sapiente ab consectetur voluptatibus quidem laboriosam repellendus, sint id aspernatur quibusdam ad numquam velit ea dolore asperiores quo necessitatibus vel non perspiciatis voluptas dicta quam magnam? Corrupti tenetur aspernatur cumque iste id non. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore vel fugiat placeat optio consectetur nihil quasi eum distinctio eos reprehenderit mollitia, natus iusto harum. Eos vitae aspernatur vero numquam eius accusantium omnis voluptatum, asperiores officia molestiae. Deleniti nemo sunt amet.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo asperiores in mollitia a atque sint nam saepe voluptas natus voluptate dolores, accusamus aliquam cupiditate consectetur tempore soluta hic ipsa neque omnis vel quos molestias. Veniam, aut. Hic minima perferendis laudantium fugit dolores tempora soluta esse cum, nemo ratione possimus sequi inventore nihil quam tenetur? Similique, explicabo nihil. Et reiciendis ex molestias obcaecati, est delectus quod repellendus iste non voluptatem adipisci libero? Perferendis earum quibusdam minus, quam maiores incidunt nisi, alias doloremque necessitatibus voluptate eum ad consectetur, impedit velit. Repellat aliquid deserunt pariatur obcaecati magni. Optio consectetur expedita soluta molestias ipsum. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate repellendus debitis fugit, asperiores obcaecati amet facilis est consequuntur, maxime quo magnam quas sapiente? Soluta quod voluptas, dolorum maiores rem expedita cumque distinctio optio neque fuga quam aut ipsum sed repudiandae dignissimos ullam vero esse dolor laboriosam impedit mollitia? Atque, adipisci. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos soluta illo placeat ex reiciendis a ea. Velit, dolor. Dolores libero, voluptate, nemo fuga, cupiditate sequi rerum aliquam minus inventore aspernatur perspiciatis! Cum, maxime! Necessitatibus porro cum fuga quam ratione corrupti autem earum, aut mollitia architecto nesciunt quo harum id hic cupiditate. Voluptate fuga eos praesentium recusandae suscipit sit iste ipsum natus quis vitae ratione similique, possimus rerum aut perspiciatis quod corporis tempore magnam doloremque neque quia perferendis. Velit facere aliquam explicabo. Ab illum excepturi, vitae esse corrupti quisquam voluptates aliquid!</p>
        </div>
    </div>
<?php
    require_once APPROOT . '/views/includes/foot.php';
?>